name: Generate guide from movistarplus.es

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
    
      - name: Grab EPG
        run: |
          pwd
          npm i dayjs --save
          npm i -g epg-grabber
          epg-grabber -o guides/es/movistar-plus.xml -c sites/movistarplus.es/movistarplus.es.config.js
        
          
      - name: commit & push
        run: |
            git init
            git config --local user.name "actions"
            git config --local user.email "action@github.com" 
            git checkout -b guides
            git add guides/*
            git commit -m "Update guides"
            git push -f -u origin guides
